### ISSUE TITLE
Add border in around the embedded view

### ISSUE THREAD

**Issue by Subhasish-Negel** [Subhasish-Negel/Data-Analysis-On-Tableau#1]
- **Add border in around the embedded view**

![Screenshot 2022-10-08 220544](https://user-images.githubusercontent.com/91432898/194717889-8e6aecb3-f995-4d11-b2c6-59abddc3da43.png)

**Comment by Areadrill** [comment]
Hi. Can I please get this assigned to me? What kind of border are you thinking of?

**Comment by Subhasish-Negel** [comment]
@Areadrill Yes ofc, please add an animated border suitable to the background animation according to your taste
